### ISSUE TITLE
Incorrect User/Secret

### ISSUE THREAD

**Issue by davidwallen** [apigeecs/ApigeeBundleReaper#1]
Should provide a meaningful error message. Currently returns:

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/davidallen/Projects/ApigeeBundleReaper/src/package/reaper_all.js:223:25)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

**Comment by ssvaidyanathan** [comment]
Fixed it. Used the same logic used in apigee-perf-summary

When the http call fails, it throws:
`401: Unauthorized with {"host":"api.enterprise.apigee.com","port":443,"path":"/v1/organizations/saisarantest/apis","method":"GET","headers":{"Accept":"application/json","Authorization":"Basic c2Fpc2FyYW4wMDdAZ21haWwuY29tOmZkZnNk"}}`

@davidwallen - Please let me know if this is ok for error scenarios. I have tested it for other scenarios too (incorrect env, incorrect org, etc)
