### ISSUE TITLE
SyntaxError: Unexpected token , bug

### ISSUE THREAD

**Issue by mpurwar** [apigeecs/ApigeeBundleReaper#3]
There is a runtime JS bug in the utility, where is throwing a syntax error of unexpected token.

Error Message:

C:\ApiGee\ApigeeBundleReaper-master\src\package\getProxyStatus.js:13
      host,
          ^
SyntaxError: Unexpected token ,
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\MKP_Projects\ApiGee\ApigeeBundleReaper-master\src\bundle-reaper.js:3:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by ssvaidyanathan** [comment]
HI @muditpurwar - I have seen this happen  when the npm version is old. To get the latest:
- Run `npm install -g npm` _(you might need to run with sudo if you see error)_
- Please go to the package directory, delete the node_modules directory and run `npm install` again.

Try after the above steps and let me know if that fixed the issue

_FYI - my node version is 4.3.0 and npm version is 3.7.4_

_Will put a note on the README about the versions as well_

**Comment by mpurwar** [comment]
Hi @ssvaidyanathan - I updated my node and npm to the latest and it worked like a charm. 

 Updating the README with at least the minimum versions required will help.

Thanks

**Comment by ssvaidyanathan** [comment]
@muditpurwar - Thanks. I have updated the README
